# 数据配置
data:
  watermarked_dir: data/train/watermarked
  clean_dir: data/train/clean
  image_size: [512, 512]
  mask_threshold: 10
  train_ratio: 0.8
  resize_mode: 'scale'  # 可选：fixed（固定尺寸）、scale（等比缩放）、pad（填充）
  keep_aspect_ratio: true  # 保持宽高比
  pad_value: 0  # 填充值
  augmentation:
    enabled: true
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]
    hflip_prob: 0.5
    vflip_prob: 0.5
    rotate_range: [-15, 15]

# 训练配置
train:
  batch_size: 16
  num_workers: 8  # 根据CPU核心数调整
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  epochs: 100
  lr: 5e-5
  weight_decay: 1e-4
  seg_loss_weight: 0.3
  edge_loss_weight: 0.1
  validation_split: 0.2
  save_interval: 10
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
  scheduler:
    type: 'onecycle'  # 可选：onecycle, reduce_on_plateau, cosine
    patience: 5
    factor: 0.5
    min_lr: 1e-6

# 运行时配置
runtime:
  device: 'cuda:1'  # 可选：cuda:0, cuda:1, cpu
  amp: true  # 自动混合精度
  gradient_clip: 1.0  # 梯度裁剪值
  seed: 42  # 随机种子
  log_interval: 10  # 日志记录间隔（批次）

# 模型配置
model:
  use_seg_branch: true
  save_dir: models/
  checkpoint: seg_unetpp.pth
  attention:
    enabled: true
    type: 'channel'  # 可选：channel, spatial, cbam
  normalization: 'batch'  # 可选：batch, group, instance

# 预测配置
predict:
  input_dir: data/input/
  output_dir: data/output/
  threshold: 0.5
  batch_size: 4
  save_visualization: true
  save_mask: true
  save_overlay: true

# 日志配置
logging:
  tensorboard: true
  log_dir: logs/
  save_images_interval: 100  # 每隔多少批次保存一次图像
  num_images_to_save: 4  # 每次保存多少张图像