data:
  data_dir: ./data
  image_size: 512
  train_dir: ./data/train
  val_dir: ./data/val
  test_dir: ./data/test
  mask_dir: ./data/mask
  test_mask_dir: ./data/test_mask
  train_csv: ./data/train.csv
  val_csv: ./data/val.csv

training:
  batch_size: 16
  epochs: 300
  learning_rate: 0.0001
  num_workers: 4
  lambda_seg: 0.5      # 分割损失权重
  lambda_edge: 0.2     # 边缘损失权重
  lr_patience: 5       # 学习率调整耐心期
  save_dir: ./checkpoints

logging:
  log_dir: ./logs