# UNet 掩码预测模型配置

# 数据配置
data:
  root_dir: '../data/train'
  watermarked_dir: '../data/train/watermarked'
  clean_dir: '../data/train/clean'
  image_size: [512, 512]
  generate_mask_threshold: 30

# 训练配置
train:
  batch_size: 4
  epochs: 300
  lr: 0.0001  # 改为明确的浮点数格式
  weight_decay: 0.0001  # 同样改为明确的浮点数格式
  save_interval: 5
  model_save_path: '../models/unet_mask_watermark.pth'
  output_dir: '../models/'
  log_interval: 10

# 模型配置
model:
  name: 'UNetPlusPlus'
  input_channels: 3
  num_classes: 1
  deep_supervision: false
  save_path: '../models/unet_mask_watermark.pth'  # 确保路径正确

# 预测配置
predict:
  input_path: '../data/input'
  output_dir: '../data/mask'
  threshold: 0.5
  post_process: true

# IOPaint集成配置
iopaint:
  model: 'lama'
  output_dir: '../data/restored'

# 流水线配置
pipeline:
  save_masks: true
  save_intermediate: false
  quality_check: true

# 运行时配置
runtime:
  device: 'cpu'