data:
  watermarked_dir: ./../data/train/watermarked
  clean_dir: ./../data/train/clean
  image_size: [512, 512]
  mask_threshold: 10
  train_ratio: 0.8
  resize_mode: 'scale'  # 可选：fixed（固定尺寸）、scale（等比缩放）、pad（填充）
  keep_aspect_ratio: true  # 保持宽高比
  pad_value: 0  # 填充值

train:
  batch_size: 16
  num_workers: 8  # 根据CPU核心数调整
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  epochs: 100
  lr: 5e-5
  device: cpu #cuda:1
  log_dir: ./../logs/watermark_remover'
  
model:
  use_seg_branch: true
  save_dir: ./../models/
  checkpoint: seg_unetpp.pth

predict:
  device: cpu #cuda:1
  input_dir: ./../data/input/
  output_dir: ./../data/output/
  threshold: 0.5