# UNet++ 模型特定配置
# 继承 common.yaml 的基础配置

# 数据路径配置
data:
  watermarked_dir: './data/train/watermarked'
  clean_dir: './data/train/clean'
  input_dir: './data/input/'
  output_dir: './data/output/'

# 训练配置覆盖
train:
  batch_size: 8
  epochs: 50
  lr: 5e-5
  seg_loss_weight: 0.3
  edge_loss_weight: 0.1

# 模型特定配置
model:
  name: 'SegGuidedUnetPP'
  use_seg_branch: true
  checkpoint: 'seg_unetpp.pth'
  attention:
    enabled: true
    type: 'channel'

# 运行时配置
runtime:
  device: 'cpu'